version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tmo-assignment-school-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14b4wgdkjg6s1"
s3_prefix = "tmo-assignment-school-app"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
